apiVersion: v1
kind: ConfigMap
metadata:
  name: numaplane-controller-config
data:
  config.yaml: |
    # Supported log levels are: VERBOSE, DEBUG, INFO, WARN. ERROR, FATAL will be printed regardless of the log level
    logLevel: INFO
    includedResources: "group=apps,kind=Deployment;\
    group=,kind=ConfigMap;group=,kind=ServiceAccount;group=,kind=Secret;group=,kind=Service;\
    group=rbac.authorization.k8s.io,kind=RoleBinding;group=rbac.authorization.k8s.io,kind=Role"
    defaultUpgradeStrategy: "pause-and-drain"
    progressive:
      defaultAssessmentSchedule:
        - kind: Pipeline
          schedule: "120,60,10"
        - kind: MonoVertex
          schedule: "120,60,10"
        - kind: InterstepBufferService
          schedule: "0,0,10"
