apiVersion: v1
kind: ConfigMap
metadata:
  name: numaplane-controller-config
data:
  config.yaml: |
    logLevel: 1
    includedResources: "group=apps,kind=Deployment;\
    group=,kind=ConfigMap;group=,kind=Secret;group=,kind=ServiceAccount;\
    group=rbac.authorization.k8s.io,kind=RoleBinding;group=rbac.authorization.k8s.io,kind=Role"