apiVersion: numaplane.numaproj.io/v1alpha1
kind: NumaflowController
metadata:
  name: numaflowcontroller-sample
  namespace: example-namespace
spec:
  #instanceID: "0" # uncomment for Progressive rollout to set Numaflow Controller instance
  version: "1.5.0"
