apiVersion: numaplane.numaproj.io/v1alpha1
kind: ISBServiceRollout
metadata:
  name: my-isbsvc
  namespace: example-namespace
spec:
  strategy:
    progressive:
      assessmentSchedule: "0,0,0,10"
  interStepBufferService:
    #uncomment for Progressive rollout to set Numaflow Controller instance:
    #metadata:
    #  annotations:
    #    numaflow.numaproj.io/instance: "0"
    spec:
      # Example from https://github.com/numaproj/numaflow/blob/main/examples/0-isbsvc-jetstream.yaml
      jetstream:
        version: 2.10.3
        persistence:
          volumeSize: 1Gi
